### ISSUE TITLE
Data Collection

### ISSUE THREAD

**Issue by niteshkumar2000** [aravindm711/ESNSE#2]
- Finding reliable source of data
- Choosing appropriate technology for scraping
- Scraping the data

**Comment by niteshkumar2000** [comment]
Moneycontrol - https://www.moneycontrol.com/news/business/stocks/
Economic times - https://economictimes.indiatimes.com/markets/stocks/news

**Comment by niteshkumar2000** [comment]
Scrapy
Installation
Installation guide — Scrapy 2.5.0 documentation

Scraping starter guide
Scrapy Tutorial — Scrapy 2.5.0 documentation

**Comment by niteshkumar2000** [comment]
Data collection from money control is done,

What next?
1. Should we preprocess the data before storing?
2. Can we use scrapy pipelines to process and push scraped data to elastic?

**Comment by aravindm711** [comment]
I'm looking into free compute resources in heroku, for performance purposes. Could come in handy in the future, if we're building a server.

**Comment by niteshkumar2000** [comment]
JSON structure of final data.
{
"title" : "",
"link" : "",
"date" : "",
"gist" : "",
"content" : ""
}

**Comment by niteshkumar2000** [comment]
> I'm looking into free compute resources in heroku, for performance purposes. Could come in handy in the future, if we're building a server.

great!

**Comment by niteshkumar2000** [comment]
https://selenium-python.readthedocs.io/getting-started.html

https://chromedriver.chromium.org/downloads

Set the driver as path variable or specify the location of the driver when instantiating the object
