### ISSUE TITLE
Storage and Indexing

### ISSUE THREAD

**Issue by niteshkumar2000** [aravindm711/ESNSE#3]
- Choosing appropriate technology to store and retrieve the data
- Structuring data into JSON
- Pushing the data to the tool
- Indexing with the tool
- Retrieving the data from the tool

**Comment by niteshkumar2000** [comment]
![image](https://user-images.githubusercontent.com/36584997/135060523-4fbf3226-158d-4a2f-8799-898cdcaa78e1.png)

**Comment by niteshkumar2000** [comment]
Installation

Elastic - https://www.elastic.co/downloads/elasticsearch

Kibana - https://www.elastic.co/downloads/kibana

Quick starter

https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started.html

https://www.elastic.co/guide/en/kibana/current/get-started.html

**Comment by niteshkumar2000** [comment]
@aravindm711  Need to write a script to preprocess data and push JSON blobs as batches so that when we retrieve the data it'll be done much faster.

**Comment by niteshkumar2000** [comment]
Also let's trigger it on spider close so the pipeline can be automated

**Comment by aravindm711** [comment]
Sure. Do you want me to look into it?

**Comment by niteshkumar2000** [comment]
Update da...looks like we need to preprocess or do the ranking, when we search for a keyword the results of IR already performs best IR algorithms and retrieves the results with score xD

**Comment by niteshkumar2000** [comment]
So we can apply only domain specific constrain on results and show the top 10 or 20..and later we can apply ML models if needed

**Comment by niteshkumar2000** [comment]
Let's push all related scripts that deal with elastic in elastic branch
